// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRxss5N5b8Hr6lZuhmLisYOK82ZjNLGI',
    appId: '1:486391599000:web:18b250042f8e764d0b65ed',
    messagingSenderId: '486391599000',
    projectId: 'hoazen-hcmut',
    authDomain: 'hoazen-hcmut.firebaseapp.com',
    storageBucket: 'hoazen-hcmut.firebasestorage.app',
    measurementId: 'G-MP40ZSC282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpl2sOQYbas12yfFTmg45K5P2Ziu0y-xg',
    appId: '1:486391599000:android:5e0ca548e247b49c0b65ed',
    messagingSenderId: '486391599000',
    projectId: 'hoazen-hcmut',
    storageBucket: 'hoazen-hcmut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLGQMAcZGqFaLf4XfJPOHU3xn4kuN8v0',
    appId: '1:486391599000:ios:6da0b046a0b0ee430b65ed',
    messagingSenderId: '486391599000',
    projectId: 'hoazen-hcmut',
    storageBucket: 'hoazen-hcmut.firebasestorage.app',
    iosBundleId: 'com.example.hoazen',
  );
}
